[project]
name = "hawcsimulator"
description="HAWCsat simulator package"
authors = [ "Daniel Zawada <daniel.zawada@usask.ca>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64", "win-64", "osx-64"]

[pypi-dependencies]
hawcsimulator = { path = ".", editable = true }
hitran-api = "*"
sf-hamilton = ">=1.87.0,<2"
skplatform = ">=0.2.17"

# Run dependencies
[dependencies]
numpy = "*"
sasktran2 = {version=">2024.11.0"}
astropy = "*"
numba = "*"
pip = "*"
xarray = "*"
netcdf4 = "*"
appdirs = "*"
jupyter = "*"
matplotlib = "*"
ruff = "*"
setuptools_scm = "*"
pre-commit = "*"

# Test dependencies
[feature.test.dependencies]
pytest = ">=8.3.3,<9"

# Doc dependencies
[feature.docs]
dependencies = {sphinx = "*", "myst-nb" = "*"}
pypi-dependencies = {sphinx_book_theme = "*", sphinx_design = "*"}

[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.standard.pypi-dependencies]
skretrieval = "*"
showlib = "*"
aliprocessing = "*"

[environments]
default = ["test", "docs", "standard"]
py311 = ["py311", "standard"]
py312 = ["py312", "standard"]

[tasks]
show-tutorial = { cmd = "jupyter notebook", cwd = "notebooks/show/tutorial" }
test = { cmd = "pytest tests/", cwd = "." }
pre-commit = { cmd = "pre-commit run -a", cwd = "." }
docs = { cmd = "sphinx-build -b html docs/source docs/build", cwd = "." }
readthedocs = { cmd = "rm -rf $READTHEDOCS_OUTPUT/html && cp -r docs/build/ $READTHEDOCS_OUTPUT/html", depends-on = ["docs"] }

dev-install-showlib = { cmd = "pip install --no-deps -e  ../show-lib", cwd = "."}
dev-install-skretrieval = { cmd = "pip install --no-deps -e ../skretrieval", cwd = "." }
dev-install-aliprocessing = { cmd = "pip install --no-deps -e ../ali-processing", cwd = "." }
dev-install-sasktran2 = { cmd = "pip install --no-deps -e ../sasktran2", cwd = "." }
